/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellTemplatesRouteImport } from './routes/_shell.templates'
import { Route as ShellUploadsRouteImport } from './routes/_shell.uploads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTemplatesRoute = ShellTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUploadsRoute = ShellUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/templates': typeof ShellTemplatesRoute
  '/uploads': typeof ShellUploadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ShellDashboardRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/templates': typeof ShellTemplatesRoute
  '/uploads': typeof ShellUploadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/templates': typeof ShellTemplatesRoute
  '/_shell/uploads': typeof ShellUploadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/reports' | '/settings' | '/templates' | '/uploads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/reports' | '/settings' | '/templates' | '/uploads'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/dashboard'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/templates'
    | '/_shell/uploads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/templates': {
      id: '/_shell/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof ShellTemplatesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/uploads': {
      id: '/_shell/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof ShellUploadsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTemplatesRoute: typeof ShellTemplatesRoute
  ShellUploadsRoute: typeof ShellUploadsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTemplatesRoute: ShellTemplatesRoute,
  ShellUploadsRoute: ShellUploadsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
